# Generated by Django 5.1 on 2024-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='media/book_images')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
