# Generated by Django 5.1 on 2024-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.IntegerField(default=100),
        ),
    ]
