# Generated by Django 5.1 on 2024-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='now_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
