# Generated by Django 5.1 on 2024-08-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_now_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='now_price',
        ),
    ]
